APP_NAME = AQZ NetPlay

HEADER = stdafx.h
PCH = $(HEADER).gch

PLUGIN_SRC = \
	client.cpp \
	client_dialog.cpp \
	common.cpp \
	connection.cpp \
	input_plugin.cpp \
	netplay_input_plugin.cpp \
	plugin_dialog.cpp \
	room.cpp \
	server.cpp \
	settings.cpp \
	user.cpp \
	util.cpp

SERVER_SRC = \
	server.cpp \
	room.cpp \
	user.cpp \
	connection.cpp \
	common.cpp

VERSION = version.h
GIT_COMMIT = $(shell git rev-parse --short HEAD)

$(VERSION): ../../../.git/index
        echo '#define APP_NAME "$(APP_NAME)"' > $(VERSION)
        echo '#define APP_VERSION "$(GIT_COMMIT)"' >> $(VERSION)
        echo '#define APP_NAME_AND_VERSION "$(APP_NAME) ($(GIT_COMMIT))"' >> $(VERSION)