#pragma once

static const size_t OVERLAY_NAMES_MP1_COUNT = 0x84;
static const char* OVERLAY_NAMES_MP1[OVERLAY_NAMES_MP1_COUNT] = {
    "Memory Match",
    "Chance Time",
    "Slot Machine",
    "Buried Treasure",    
    "Treasure Divers",    
    "Shell Game",    
    "Unused Minigame 0",  
    "Hot Bob-Omb",   
    "Unused Minigame 1",  
    "Pipe Maze",
    "Ghost Guess",   
    "Musical Mushroom",   
    "Pedal Power",   
    "Crazy Cutter",  
    "Face Lift",
    "Whack-a-Plant", 
    "Bash n' Cash",  
    "Bowl Over",
    "Ground Pound",  
    "Balloon Burst", 
    "Coin Block Blitz",   
    "Coin Block Bash",    
    "Skateboard Skamper", 
    "Box Mountain Mayhem",
    "Platform Peril",
    "Teetering Towers",   
    "Mushroom Mixup",
    "Hammer Drop",  
    "Grab Bag",
    "Bobsled Run",  
    "Bumper Balls", 
    "Tightrope Treachery",    
    "Knock Block Tower", 
    "Tipsy Tourney",
    "Bombs Away",   
    "Crane Game",   
    "Flower Shower",
    "Slot Car Derby",    
    "Mario Bandstand",   
    "Desert Dash",  
    "Shy Guy Says", 
    "Limbo Dance",  
    "",   
    "Cast Aways",   
    "Key-pa-way",   
    "Running of the Bulb",    
    "Hot Rope Jump",
    "Handcar Havoc",
    "Deep Sea Divers",   
    "Piranhas Pursuit",  
    "Tug o' War",   
    "Paddle Battle",
    "Bumper Ball Maze",  
    "",   
    "DK's Jungle Adventure",  
    "Peach's Birthday Cake",  
    "Yoshi's Tropical Island",
    "Wario's Battle Canyon",  
    "Luigi's Engine Room",    
    "Mario's Rainbow Castle", 
    "Bowser's Magma Mountain",
    "Eternal Star", 
    "First Map",    
    "",   
    "",   
    "Yoshi's Tropical Island",
    "Final Results",
    "Final Results",
    "",   
    "",   
    "",   
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Opening Cutscene",
    "",
    "Staff Credits",
    "",
    "",
    "Boot Logos",
    "Boot Logos",
    "",
    "Mushroom Village",
    "Into the Warp Pipe",
    "Minigame House",
    "Mushroom Shop",
    "Mushroom Bank",
    "Options House",
    "Minigame Instructions",
    "Testing Room",
    "Minigame Island",
    "Minigame Island",
    "",
    "",
    "",
    "",
    "Minigame Island",
    "Minigame Island",
    ""
    "",
    "Minigame Stadium",
    "",
    "Minigame Stadium",
    "",
    "Minigame Stadium",
    "Minigame Stadium",
    "",
    "Mini Game Stadium",
    "",
    ""
};

static const size_t OVERLAY_NAMES_MP2_COUNT = 0x73;
static const char* OVERLAY_NAMES_MP2[OVERLAY_NAMES_MP2_COUNT] = {
    "Debug Menu",              
    "Bowser Slots",        
    "Roll Out The Barrels",  
    "Coffin Congestion",   
    "Hammer Slammer",      
    "Give Me a Brake",       
    "Mallet Go Round",      
    "Grab Bag",            
    "Lava Tile Isle",       
    "Bumper Balloon Cars",  
    "Rakin Em In",          
    "Day at the Races",      
    "Hot Rope Jump",        
    "Hot Bob Omb",          
    "Bowl Over",           
    "Rainbow Run",         
    "Crane Game",          
    "Move to the Music",     
    "Bob-omb Barrage",      
    "Look Away",           
    "Shock Drop Or Roll",    
    "Lights Out",          
    "Filet Relay",         
    "Archerival",         
    "Toad Bandstand",      
    "Bobsled Run",         
    "Handcar Havoc",       
    "Ballon Burst",        
    "Sky Pilots",          
    "Speed Hockey",        
    "Cake Factory",        
    "Dungeon Dash",        
    "Magnet Carta",        
    "Face Lift",           
    "ShellShocked",       
    "Crazy Cutters",       
    "Toad In The Box",       
    "Mecha Marathon",      
    "Roll Call",           
    "Abandon Ship",        
    "Platform Peril",      
    "Totem Pole Pound",     
    "Bumper Balls",        
    "Bombs Away",          
    "Tipsy Tourney",       
    "Honeycomb Havoc",     
    "Hexagon Heat",        
    "Skateboard Scamper",  
    "Slot Car Derby",       
    "Shy Guy Says",         
    "Sneak N Snore",        
    "Drivers Ed",          
    "",         
    "Looney Lumberjacks",  
    "Dizzy Dancing",       
    "Tile Driver",         
    "Quicksand Cache",     
    "Bowsers Big Blast",    
    "Torpedo Targets",     
    "Destruction Duet",    
    "Deep Sea Salvage",     
    "",            
    "",            
    "Quick Draw Corks",         
    "",         
    "",            
    "Saber Swipes",         
    "",            
    "",            
    "Western Land",          
    "Pirate Land",          
    "Horror Land",          
    "Space Land",          
    "Mystery Land",          
    "Bowser Land",          
    "Mini-Game Stadium",          
    "Mini-Game Coaster",          
    "Rules Land",          
    "",            
    "",            
    "",            
    "",            
    "",            
    "",            
    "",            
    "",            
    "",            
    "Boot Logos",          
    "Minigame Park",  
    "",            
    "",            
    "",            
    "",            
    "",            
    "",            
    "",            
    "",            
    "",            
    "Title Screen And Intro",
    "",            
    "",            
    "",            
    "",            
    "",            
    "",            
    "",            
    "",            
    "",            
    "",            
    "Minigame Coaster"
    "Minigame Coaster",
    "",      
    "Results",            
    "",            
    "Credits"             
};


static const size_t OVERLAY_NAMES_MP3_COUNT = 0x81;
static const char* OVERLAY_NAMES_MP3[OVERLAY_NAMES_MP3_COUNT] = {
    "",
    "",
    "Hand, Line and Sinker", 
    "Coconut Conk",
    "Spotlight Swim",
    "Boulder Ball",
    "Crazy Cogs",
    "Hide and Sneak",
    "Ridiculous Relay",
    "Thwomp Pull",
    "River Raiders",
    "Tidal Toss",
    "Eatsa Pizza",
    "Baby Bowser Broadside",
    "Pump, Pump and Away"
    "Hyper Hydrants",
    "Picking Panic",
    "Cosmic Coaster",
    "Puddle Paddle",
    "Etch 'n' Catch",
    "Log Jam",
    "Slot Synch",
    "Treadmill Grill",
    "Toadstool Titan",
    "Aces High",
    "Bounce 'n' Trounce",
    "Ice Rink Risk",
    "Locked Out",
    "Chip Shot Challenge",
    "Parasol Plummet",
    "Messy Memory",
    "Picture Imperfect",
    "Mario's Puzzle Party",
    "The Beat Goes On", 
    "M.P.I.Q.",
    "Curtain Call",
    "Water Whirled", 
    "Frigid Bridges",
    "Awful Tower",
    "Cheep Cheep Chase",
    "Pipe Cleaners",
    "Snowball Summit",
    "All Fired Up",
    "Stacked Deck",
    "Three Door Monty",
    "Rockin' Raceway",
    "Merry-Go-Chomp",
    "Slap Down",
    "Storm Chasers",
    "Eye Sore",
    "Vine With Me",
    "Popgun Pickoff",   
    "End of the Line",  
    "Bowser Toss",
    "Baby Bowser Bonkers"
    "Motor Rooter",
    "Silly Screws",
    "Crowd Cover", 
    "Tick Tock Hop",
    "Fowl Play",   
    "Winner's Wheel",   
    "Hey Batter Batter",
    "Bobbing Bow-Loons",
    "Dorrie Dip"
    "Swinging With Sharks",
    "Swing 'n' Swipe",
    "Stardust Battle",
    "Game Guy's Roulette",
    "Game Guy's Lucky 7",
    "Game Guy's Magic Boxes",
    "Game Guy's Sweet Surprise", 
    "Dizzy Dinghies",
    "The Star Lift",
    "Chilly Waters",
    "Deep Bloober Sea",
    "Spiny Desert",
    "Woody Woods",
    "Creepy Cavern",
    "Waluigi's Island",
    "",
    "Final Results",
    "",
    "",
    "",   
    "",
    "",
    "Board Results",
    "The Star Lift",
    "The Star Lift",
    "Boot Logos",
    "Debug Menu",
    "The Star Lift",
    "Gate Guy",
    "Arrowhead",
    "Pipesqueak",
    "Blowhard",
    "Mr. Mover",
    "Backtrack",
    "",
    "Duel Result",
    "Duel Result",
    "",
    "",
    "Story Debug",
    "System Error",
    "",
    "Mini-Game Mode",
    "",
    "Story Mode Cutscene",
    "Story Mode Cutscene",
    "Story Mode Cutscene",
    "Story Mode Cutscene",
    "Story Mode Cutscene",
    "",
    "",
    "",
    "",
    "",
    "Opening Cutscene",
    "",
    "Mode Select",
    "Mini-Game Setup",
    "File Select",
    "Opening Cutscene",
    "Options",
    "Staff Credits",
    "Story Results",
    "",
    "Select Menu"
};